### ISSUE TITLE
CastBars - 'charge' fill colors are backwards

### ISSUE THREAD

**Issue by Toludin** [ForgeUI/ForgeUI#145]
I always felt like I had a difficult time tracking my Charged Shot 'charge' status, and just realized that I think it's because the fill colors for a charged ability are reversed. Rather than starting black (or whatever your background is) and filling with your cast bar color, it starts fully colored and fills with black segments.

I changed this locally and find it greatly helps me, but I'm not sure if this was an intended decision on your end, or if perhaps you don't play many characters with charge abilities and hadn't noticed. If you do like the way it currently is, would you be okay with me adding an option for this? Otherwise, if you'd like it to just change, I can create a fork and push my changes.

**Comment by adamjedlicka** [comment]
Yeah this is intended. Colors are ok but instead of starting with empty bar that fills up, it starts as full bar that empties out and from other direction as normal cast bar. Me reasoning behind this is if you set cast bar to bright color or dark background with current 'charge'bar you will start with fully bright bar which has less and less bright parts but still you can see the bright color easily. At the end of the cast all bright colors disappear and you see only dark color which means you finished your casting and you can stop holding the button. If it would be same or similar as normal castbar you won't know exactly when you stopped casting unless you will be looking at the bar. If you want to make it as an option to change it you are free to do it, but I would like this style to be default.
