### ISSUE TITLE
NamePlates - Wrong position for name

### ISSUE THREAD

**Issue by adamjedlicka** [ForgeUI/ForgeUI#255]
When settings for show name and show bars is set to never, after /reloadui and clicking on that uni type this happens: [http://i.imgur.com/WGNEaKu.png](http://i.imgur.com/WGNEaKu.png)

Code for handling name is here: [https://github.com/ForgeUI/ForgeUI/blob/master/ForgeUI_Nameplates/ForgeUI_Nameplates.lua#L678](https://github.com/ForgeUI/ForgeUI/blob/master/ForgeUI_Nameplates/ForgeUI_Nameplates.lua#L678)

If during loading bShow is set atleast once to true name will gaet positioned as expected. But for some reason if during loading name is invisible it gets moved (dunno how, when commented every SetAnchorOffsets repositioning still happens).

Maybe soemting in XML file is wrong?

**Comment by veex-ua** [comment]
ok I figured that commiting this might rollback some of the changes you did to "NameRewardContainer" if there were any so not gonna Pull-request. Just see comment:

It seems issue is indeed with XML file but I couldn't figure out what exactly causing it. My guess the problem is with WorldFixedWindow class and how it reposition children windows. Maybe this is why Carbine using "containers" for everything that changing visibility state.

What I did is rolled back to "NameRewardContainer" from XML file that you've been using in v0.48 and changed wndReferences in code for old format. Rest of the XML file is untouched.
