### ISSUE TITLE
Fast SkillSwitch

### ISSUE THREAD

**Issue by GedasFX** [ForgeUI/ForgeUI#307]
There is an addon that is not being that well maintained called SkillSwitch. All it does is allows you to switch a skill by creating a dropdown of preselected skills. Would it be fiesable for forge ui to support it natively?

**Comment by veex-ua** [comment]
Kinda funny but I have exactly what you're looking for :smile: 
I've named it ForgeUI_ActionSets and the idea was to combine SkillSwitch and VinceBuild into single ForgeUI addon. Unfortunately I haven't had enough time recently to work on this addon so at the moment it only has SkillSwitch functionality. I'll release it later today/tomorrow in its current state so stay tuned.

**Comment by adamjedlicka** [comment]
Wow look dope. Great work. Btw what "It will NOT work with 'ForgeUI_ActionBarsExt'!" means? That it won't work for new special action bars or it is not compatible with ActionBarsExt? If it's not compatible I could look into it and fix it.

**Comment by veex-ua** [comment]
I'm not sure about compatibility as I haven't really tested them together that much, but it certainly won't work for custom buttons due to how it retrieve action buttons table (calls for tAddon:API_GetTBars).
There is also some functionality questions. Menu buttons are placed on top of action buttons with no option to change their position which means, for the moment, it only supports horizontal oriented action bars. Another issue is that there can be scenarios where there is no room for menu buttons at all (i.e 3x3 square buttons layout with no room for very middle button).
Anyways, it's definitely possible to make them work together with some basic functionality and I had plans to look into this, but haven't had a chance lately. Repo is up for this addon so feel free to add/change whatever you think will fit.

**Comment by GedasFX** [comment]
This addon worked perfectly and had everything I could ever wanted, however just now, for no reason at all, it started to no longer be able to launch.

...tar\Addons\ForgeUI_ActionSets\ForgeUI_ActionSets.lua:15: attempt to index field 'ForgeLibs' (a nil value)
stack trace:
	...tar\Addons\ForgeUI_ActionSets\ForgeUI_ActionSets.lua:15: in main chunk

I do not have automatic updates and did not change anything with addons. Maybe I somehow in my sleepgaming I disabled a dependancy?

**Comment by veex-ua** [comment]
Have you tried to disable ActionSets addon? Does rest of ForgeUI loading properly without it?

**Comment by GedasFX** [comment]
Sorry, wasn't able to get to the PC on the weekend.
To answer that question, yes. The error only occurs on initialization (/reloadui) and the error message can only be seen on the addons tab in esc menu and by clicking Show Errors on the addon with big round red circle next to its name.

**Comment by veex-ua** [comment]
Well, this is very strange error and I don't really know what might causing it for you. Try to disable every non ForgeUI addons (except Carbine ones) and see if it fix anything. If not then try to reinstall ForgeUI.

**Comment by GedasFX** [comment]
Well. I logged in today and sure enough, the addon is working as if nothing happened. I guess the issue is solved? 😄 
Anyway, thanks for the addon!
